checks:
  php:
    code_rating: true

filter:
  excluded_paths:
    - tests/*
    - vendor/*

build:

  environment:
    php: '7.4'

  dependencies:
    before:
      - composer install
      - mkdir -p build/logs

  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover build/logs/clover.xml'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'clover'
