language: php

matrix:
  exclude:
    - env: LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
      php: 7.2
    - env: LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
      php: 7.1
    - env: LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
      php: 7.1
    - env: LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
      php: 7.1

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - ./vendor
    - $HOME/.composer/cache

env:
  - LARAVEL_VERSION=^8.0 TESTBENCH_VERSION=^6.0
  - LARAVEL_VERSION=^7.0 TESTBENCH_VERSION=^5.0
  - LARAVEL_VERSION=^6.0 TESTBENCH_VERSION=^4.0
  - LARAVEL_VERSION=5.8.* TESTBENCH_VERSION=3.8.*

before_script:
  - composer self-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" "orchestra/testbench:${TESTBENCH_VERSION}" --no-update
  - if [ "$PHPUNIT_VERSION" != "" ]; then composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update; fi;
  - composer update
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
