name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4, '8.0', 8.1]
        lib:
          - { laravel: ^10.0 }
          - { laravel: ^9.0 }
          - { laravel: ^8.0 }
          - { laravel: ^7.0 }
          - { laravel: ^6.0 }
          - { laravel: ^6.0, flags: --prefer-lowest }
        exclude:
          - { php: 8.1, lib: { laravel: ^7.0 } }
          - { php: 8.1, lib: { laravel: ^6.0 } }
          - { php: 8.1, lib: { laravel: ^6.0, flags: --prefer-lowest } }
          - { php: 8.0, lib: { laravel: ^10.0 } }
          - { php: 7.4, lib: { laravel: ^10.0 } }
          - { php: 7.4, lib: { laravel: ^9.0 } }
          - { php: 7.3, lib: { laravel: ^10.0 } }
          - { php: 7.3, lib: { laravel: ^9.0 } }

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - run: composer require "laravel/framework:${{ matrix.lib.laravel }}" --dev ${{ matrix.lib.flags }}
      - run: mkdir -p build/logs
      - run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Upload Coverage
        uses: nick-invision/retry@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: 'true'
          COVERALLS_FLAG_NAME: 'laravel:${{ matrix.lib.laravel }}'
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            composer global require php-coveralls/php-coveralls
            php-coveralls --coverage_clover=build/logs/clover.xml -v

  coverage-aggregation:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Aggregate Coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
